# Generated by Django 2.2.7 on 2019-11-06 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0002_auto_20191106_1220'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ('-published',)},
        ),
        migrations.RenameField(
            model_name='post',
            old_name='publish',
            new_name='published',
        ),
        migrations.AlterField(
            model_name='post',
            name='text_min',
            field=models.CharField(max_length=300, verbose_name='Краткое описание'),
        ),
    ]
